# Generated by Django 5.1.3 on 2024-11-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasfiscaiscompra',
            name='frete',
        ),
        migrations.AddField(
            model_name='notasfiscaiscompra',
            name='Produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_compra', to='contas.produtos'),
        ),
    ]
