# Generated by Django 5.1.3 on 2025-01-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxocaixalancamento',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_fluxo', to='contas.contasbancarias'),
        ),
        migrations.AddField(
            model_name='fluxocaixalancamento',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_fluxo', to='contas.fornecedores'),
        ),
        migrations.AlterField(
            model_name='fluxocaixalancamento',
            name='categoria',
            field=models.CharField(choices=[('vendas', 'Vendas'), ('aluguel', 'Aluguel'), ('servicos', 'Serviços'), ('suprimentos', 'Suprimentos'), ('despesas_operacionais', 'Despesas Operacionais'), ('despesas_administrativas', 'Despesas Administrativas'), ('impostos', 'Impostos'), ('locacao_maquinas', 'Locação de Máquinas'), ('manutencao', 'Manutenção'), ('folha_pagamento', 'Folha de Pagamento'), ('outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fluxocaixalancamento',
            name='fonte_tipo',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('conta_receber', 'Conta a Receber'), ('conta_pagar', 'Conta a Pagar'), ('nfe', 'Nota Fiscal de Entrada'), ('nfs', 'Nota Fiscal de Saída'), ('nfserv', 'Nota Fiscal de Serviço'), ('estorno', 'Estorno'), ('outro', 'Outro')], max_length=20),
        ),
    ]
