# Generated by Django 5.1.3 on 2024-11-20 07:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_remove_notasfiscaiscompra_frete_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensNfVenda',
            new_name='ItensNfSaida',
        ),
        migrations.RenameModel(
            old_name='NotasFiscaisVenda',
            new_name='NotasFiscaisSaida',
        ),
        migrations.RemoveField(
            model_name='notasfiscaiscompra',
            name='Produto',
        ),
        migrations.RemoveField(
            model_name='notasfiscaiscompra',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='movimentacoesestoque',
            name='nota_fiscal_compra',
        ),
        migrations.RemoveField(
            model_name='lotes',
            name='nota_fiscal_compra_id',
        ),
        migrations.RenameField(
            model_name='movimentacoesestoque',
            old_name='nota_fiscal_venda',
            new_name='nota_fiscal_saida',
        ),
        migrations.AlterModelTable(
            name='itensnfsaida',
            table='itens_nf_saida',
        ),
        migrations.AlterModelTable(
            name='notasfiscaissaida',
            table='notas_fiscais_saida',
        ),
        migrations.CreateModel(
            name='NotasFiscaisEntrada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_nota', models.CharField(db_index=True, max_length=20)),
                ('serie_nota', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo_frete', models.CharField(blank=True, max_length=10, null=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('valor_produtos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_calculo_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_icms_st', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('base_calculo_st', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outros_encargos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('chave_nfe', models.CharField(blank=True, db_index=True, max_length=44, null=True)),
                ('protocolo', models.CharField(blank=True, max_length=20, null=True)),
                ('natureza_operacao', models.CharField(blank=True, max_length=100, null=True)),
                ('cfop', models.CharField(blank=True, max_length=5, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('condicoes_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('parcelas', models.CharField(blank=True, max_length=100, null=True)),
                ('operacao', models.CharField(blank=True, max_length=50, null=True)),
                ('comprador', models.CharField(blank=True, max_length=100, null=True)),
                ('operador', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('Produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_entrada', to='contas.produtos')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_entrada', to='contas.fornecedores')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de entrada',
                'verbose_name_plural': 'Notas Fiscais de entrada',
                'db_table': 'notas_fiscais_entrada',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItensNfEntrada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=15, null=True, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Valor Total')),
                ('percentual_ipi', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Percentual IPI')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('aliquota', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Alíquota')),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Desconto')),
                ('cfop', models.CharField(blank=True, max_length=5, null=True, verbose_name='CFOP')),
                ('base_substituicao', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Base de Cálculo Substituição')),
                ('icms_substituicao', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='ICMS Substituição')),
                ('outras_despesas', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Outras Despesas')),
                ('frete', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Frete')),
                ('aliquota_substituicao', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Alíquota Substituição')),
                ('ncm', models.CharField(blank=True, max_length=10, null=True, verbose_name='NCM')),
                ('controle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Controle')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_nf_entrada', to='contas.produtos', verbose_name='Produto')),
                ('nota_fiscal', models.ForeignKey(db_column='nota_fiscal_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contas.notasfiscaisentrada', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Item da NFE',
                'verbose_name_plural': 'Itens da NFE',
                'db_table': 'itens_nf_entrada',
                'ordering': ['nota_fiscal', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lotes',
            name='nota_fiscal_entrada_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.notasfiscaisentrada'),
        ),
        migrations.AddField(
            model_name='movimentacoesestoque',
            name='nota_fiscal_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.notasfiscaisentrada'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contas.notasfiscaisentrada'),
        ),
        migrations.DeleteModel(
            name='ItensNfCompra',
        ),
        migrations.AddIndex(
            model_name='notasfiscaisentrada',
            index=models.Index(fields=['data_emissao'], name='notas_fisca_data_em_91a4af_idx'),
        ),
        migrations.AddIndex(
            model_name='notasfiscaisentrada',
            index=models.Index(fields=['data_entrada'], name='notas_fisca_data_en_e9742c_idx'),
        ),
        migrations.AddIndex(
            model_name='notasfiscaisentrada',
            index=models.Index(fields=['fornecedor', 'numero_nota'], name='notas_fisca_fornece_e88b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='notasfiscaisentrada',
            index=models.Index(fields=['id'], name='notas_fisca_id_0e941a_idx'),
        ),
        migrations.AddConstraint(
            model_name='notasfiscaisentrada',
            constraint=models.UniqueConstraint(fields=('fornecedor', 'numero_nota', 'serie_nota'), name='unique_nota_fiscal_fornecedor'),
        ),
        migrations.AddIndex(
            model_name='itensnfentrada',
            index=models.Index(fields=['nota_fiscal'], name='itens_nf_en_nota_fi_f10a83_idx'),
        ),
        migrations.AddIndex(
            model_name='itensnfentrada',
            index=models.Index(fields=['produto'], name='itens_nf_en_produto_e52ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='itensnfentrada',
            index=models.Index(fields=['data'], name='itens_nf_en_data_2a5ee2_idx'),
        ),
        migrations.DeleteModel(
            name='NotasFiscaisCompra',
        ),
    ]
