# Generated by Django 5.1.3 on 2025-01-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_fluxocaixalancamento_conta_bancaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratoslocacao',
            old_name='incio',
            new_name='inicio',
        ),
    ]
