# Generated by Django 5.1.3 on 2024-11-20 07:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_rename_itensnfvenda_itensnfsaida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasfiscaissaida',
            options={'ordering': ['-data'], 'verbose_name': 'Nota Fiscal de Saída', 'verbose_name_plural': 'Notas Fiscais de Saída'},
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='data_emissao',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='especie_volumes',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='frete',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='modalidade_frete',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='peso_total',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='serie_nota',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='notasfiscaissaida',
            name='volumes',
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='base_calculo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Base de Cálculo'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='cfop',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='CFOP'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Comissão'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='condicoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condições de Pagamento'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='detalhes',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='finalidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Finalidade'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='formulario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Formulário'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='imposto_federal_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Imposto Federal Total'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='n_serie',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Série'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='nf_referencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NF Referência'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='operacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='operador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='outras_despesas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Outras Despesas'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='parcelas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parcelas'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='percentual_icms',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Percentual de ICMS'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True, verbose_name='Peso'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='seguro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='tipo_frete',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Frete'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='val_ref',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor de Referência'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='valor_icms_fonte',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor do ICMS Fonte'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='valor_produtos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor dos Produtos'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='valor_total_nota',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total da Nota'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_vendedor', to='contas.funcionarios', verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='notasfiscaissaida',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_saida', to='contas.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='numero_nota',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Número da NF'),
        ),
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_saida', to='contas.transportadoras', verbose_name='Transportadora'),
        ),
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor do Frete'),
        ),
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='valor_icms',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor do ICMS'),
        ),
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='valor_ipi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor do IPI'),
        ),
        migrations.AddIndex(
            model_name='notasfiscaissaida',
            index=models.Index(fields=['numero_nota'], name='notas_fisca_numero__a3370b_idx'),
        ),
        migrations.AddIndex(
            model_name='notasfiscaissaida',
            index=models.Index(fields=['data'], name='notas_fisca_data_4a6a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='notasfiscaissaida',
            index=models.Index(fields=['cliente'], name='notas_fisca_cliente_9ef575_idx'),
        ),
        migrations.AddIndex(
            model_name='notasfiscaissaida',
            index=models.Index(fields=['vendedor'], name='notas_fisca_vendedo_d71f34_idx'),
        ),
        migrations.AddConstraint(
            model_name='notasfiscaissaida',
            constraint=models.UniqueConstraint(fields=('numero_nota', 'n_serie'), name='unique_nfs_numero_serie'),
        ),
    ]
