# Generated by Django 5.1.3 on 2025-01-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_rename_incio_contratoslocacao_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxocaixalancamento',
            name='subcategoria',
            field=models.CharField(choices=[('suprimentos', 'Suprimentos'), ('maquinas', 'Máquinas'), ('despesas_operacionais', 'Despesas Operacionais'), ('despesas_administrativas', 'Despesas Administrativas'), ('impostos', 'Impostos'), ('locacao_maquinas', 'Locação de Máquinas'), ('manutencao', 'Manutenção'), ('folha_pagamento', 'Folha de Pagamento'), ('outros', 'Outros')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fluxocaixalancamento',
            name='categoria',
            field=models.CharField(choices=[('vendas', 'Vendas'), ('aluguel', 'Aluguel'), ('servicos', 'Serviços'), ('compra', 'Compra'), ('devolucao', 'Devolução'), ('comodato', 'Comodato'), ('simplesRemessa', 'Simples Remessa'), ('adiantamento', 'Adiantamento')], max_length=50),
        ),
    ]
