# Generated by Django 5.2.1 on 2025-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_fluxocaixalancamento_subcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tipo_pessoa',
            field=models.CharField(blank=True, default='F', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='tipo_pessoa',
            field=models.CharField(blank=True, default='F', max_length=1, null=True),
        ),
    ]
