# Generated by Django 5.1.3 on 2024-11-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_notasfiscaissaida_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='cfop',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP'),
        ),
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='n_serie',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série'),
        ),
    ]
