# Generated by Django 5.1.3 on 2025-09-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_clientes_tipo_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasfiscaissaida',
            name='nf_referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NF Referência'),
        ),
    ]
