# Generated by Django 5.1.3 on 2024-11-20 08:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_notasfiscaissaida_cfop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasfiscaisconsumo',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='notasfiscaisconsumo',
            name='transportadora',
        ),
        migrations.AlterModelOptions(
            name='itensnfsaida',
            options={'ordering': ['nota_fiscal', 'id'], 'verbose_name': 'Item da NFS', 'verbose_name_plural': 'Itens da NFS'},
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='aliquota_icms',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='aliquota_ipi',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='base_calculo_icms',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='cfop',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='ncm',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='nota_fiscal_id',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='produto_id',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='valor_icms',
        ),
        migrations.RemoveField(
            model_name='itensnfsaida',
            name='valor_ipi',
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='aliquota',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Alíquota'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='controle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Controle'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='cst_a',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CST A'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='cst_b',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='CST B'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='frete',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Frete'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='nota_fiscal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contas.notasfiscaissaida', verbose_name='Nota Fiscal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='outras_despesas',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Outras Despesas'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='percentual_ipi',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Percentual IPI'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='itens_nf_saida', to='contas.produtos', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='reducao',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Redução'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='seguro',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Seguro'),
        ),
        migrations.AddField(
            model_name='itensnfsaida',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itensnfsaida',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='itensnfsaida',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=15, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itensnfsaida',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='itensnfsaida',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Valor Unitário'),
        ),
        migrations.AddIndex(
            model_name='itensnfsaida',
            index=models.Index(fields=['nota_fiscal', 'produto'], name='itens_nf_sa_nota_fi_b39e22_idx'),
        ),
        migrations.AddIndex(
            model_name='itensnfsaida',
            index=models.Index(fields=['data'], name='itens_nf_sa_data_90801f_idx'),
        ),
        migrations.AddIndex(
            model_name='itensnfsaida',
            index=models.Index(fields=['produto'], name='itens_nf_sa_produto_4f562e_idx'),
        ),
        migrations.DeleteModel(
            name='NotasFiscaisConsumo',
        ),
    ]
