# Generated by Django 5.1.3 on 2025-09-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_notasfiscaissaida_nf_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoesestoque',
            name='data_movimentacao',
            field=models.DateTimeField(),
        ),
    ]
