# Generated by Django 5.1.3 on 2024-11-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_notasfiscaisservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notasfiscaisservico',
            name='cfop',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CFOP'),
        ),
    ]
