# Generated by Django 5.2.6 on 2025-09-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_movimentacoesestoque_data_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
