# Generated by Django 5.2.6 on 2025-09-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_fornecedores_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='especificacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
