# Generated by Django 5.1.3 on 2024-11-20 09:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_alter_notasfiscaisservico_n_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensNfServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('servico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Servico')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=15, null=True, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Valor Total')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contas.notasfiscaisservico', verbose_name='Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Item da NFS',
                'verbose_name_plural': 'Itens da NFS',
                'db_table': 'itens_nf_servico',
                'ordering': ['nota_fiscal', 'id'],
                'indexes': [models.Index(fields=['nota_fiscal', 'servico'], name='itens_nf_se_nota_fi_54681a_idx'), models.Index(fields=['data'], name='itens_nf_se_data_f292a4_idx'), models.Index(fields=['servico'], name='itens_nf_se_servico_705202_idx')],
            },
        ),
    ]
