# Generated by Django 6.0.2 on 2026-02-04 18:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_fornecedores_especificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasFiscaisConsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_nota', models.CharField(blank=True, max_length=20, null=True)),
                ('data_emissao', models.DateTimeField(blank=True, null=True)),
                ('valor_produtos', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('base_calculo_icms', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('modalidade_frete', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_icms', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_ipi', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_icms_st', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('condicoes_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cfop', models.CharField(blank=True, max_length=10, null=True)),
                ('formulario', models.CharField(blank=True, max_length=50, null=True)),
                ('data_conhecimento', models.DateTimeField(blank=True, null=True)),
                ('data_selo', models.DateTimeField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(blank=True, null=True)),
                ('tipo_nota', models.CharField(blank=True, max_length=50, null=True)),
                ('chave_nfe', models.CharField(blank=True, max_length=100, null=True)),
                ('serie_nota', models.CharField(blank=True, max_length=10, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_consumo', to='contas.fornecedores')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Consumo',
                'verbose_name_plural': 'Notas Fiscais de Consumo',
                'db_table': 'notas_fiscais_consumo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(default='2025-01-01')),
                ('quantidade_inicial', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('valor_unitario_inicial', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('valor_total_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('data_calculo', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.produtos')),
            ],
            options={
                'db_table': 'estoque_inicial',
                'indexes': [models.Index(fields=['produto'], name='estoque_ini_produto_791c47_idx'), models.Index(fields=['data_inicial'], name='estoque_ini_data_in_6c23a0_idx')],
                'unique_together': {('produto', 'data_inicial')},
            },
        ),
    ]
