# Generated by Django 6.0.2 on 2026-02-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0010_notasfiscaisconsumo_estoqueinicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasfiscaisentrada',
            name='operacao',
        ),
    ]
