# Generated by Django 6.0.2 on 2026-02-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_remove_notasfiscaisentrada_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasfiscaisentrada',
            name='operacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
