# Generated by Django 5.1.3 on 2024-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_alter_itensnfservico_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensnfservico',
            name='servico',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Servico'),
        ),
    ]
