# Generated by Django 6.0.2 on 2026-02-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_notasfiscaisentrada_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasfiscaisentrada',
            name='frete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_entrada', to='contas.fretes'),
        ),
    ]
