# Generated by Django 5.1.3 on 2024-11-20 10:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_alter_itensnfservico_servico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contaspagar',
            options={'ordering': ['-data', '-vencimento'], 'verbose_name': 'Conta a Pagar', 'verbose_name_plural': 'Contas a Pagar'},
        ),
        migrations.RemoveField(
            model_name='contaspagar',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='contaspagar',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='contaspagar',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='contaspagar',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='contaspagar',
            name='multa',
        ),
        migrations.RemoveField(
            model_name='contaspagar',
            name='nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='contaspagar',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='condicoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condições de Pagamento'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='confirmacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirmação'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='historico',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Pagamento'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='numero_duplicata',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Duplicata'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='tarifas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Tarifas'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='valor_total_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total Pago'),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='vencimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='contas.fornecedores', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Juros'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Original'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Pago'),
        ),
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(db_index=True, max_length=10, verbose_name='Código do Banco')),
                ('nome_banco', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('numero', models.CharField(max_length=20, verbose_name='Número da Conta')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'db_table': 'contas_bancarias',
                'ordering': ['nome_banco', 'agencia', 'numero'],
                'indexes': [models.Index(fields=['banco'], name='contas_banc_banco_575918_idx'), models.Index(fields=['agencia', 'numero'], name='contas_banc_agencia_55540b_idx')],
            },
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='contas.contasbancarias', verbose_name='Conta Bancária'),
        ),
        migrations.AddIndex(
            model_name='contaspagar',
            index=models.Index(fields=['data'], name='contas_paga_data_a9a7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='contaspagar',
            index=models.Index(fields=['vencimento'], name='contas_paga_vencime_ad225e_idx'),
        ),
        migrations.AddIndex(
            model_name='contaspagar',
            index=models.Index(fields=['fornecedor'], name='contas_paga_fornece_f7c66f_idx'),
        ),
        migrations.AddIndex(
            model_name='contaspagar',
            index=models.Index(fields=['status'], name='contas_paga_status_2f6c02_idx'),
        ),
        migrations.AddIndex(
            model_name='contaspagar',
            index=models.Index(fields=['data_pagamento'], name='contas_paga_data_pa_2d4a16_idx'),
        ),
    ]
