# Generated by Django 5.1.3 on 2024-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_alter_contaspagar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasbancarias',
            name='agencia',
            field=models.CharField(max_length=20, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='contasbancarias',
            name='banco',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Código do Banco'),
        ),
    ]
