# Generated by Django 6.0.2 on 2026-02-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_notasfiscaisentrada_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='especificacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
