# Generated by Django 5.1.3 on 2024-11-20 10:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0014_alter_contasbancarias_agencia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contasreceber',
            options={'ordering': ['-data', '-vencimento'], 'verbose_name': 'Conta a Receber', 'verbose_name_plural': 'Contas a Receber'},
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='data_recebimento',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='forma_recebimento',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='multa',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='nota_fiscal',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='valor_recebido',
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='cartorio',
            field=models.BooleanField(default=False, verbose_name='Em Cartório'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='comanda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Comanda'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='condicoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condições de Pagamento'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='confirmacao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Confirmação'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='contas.contasbancarias', verbose_name='Conta Bancária'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='data_pagto_factory',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Pagamento Factory'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='factory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Factory'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='historico',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='impresso',
            field=models.BooleanField(default=False, verbose_name='Impresso'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Pagamento'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='nosso_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nosso Número'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='protesto',
            field=models.BooleanField(default=False, verbose_name='Protestado'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='recebido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Recebido'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='repassado_factory',
            field=models.BooleanField(default=False, verbose_name='Repassado para Factory'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='status_factory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Factory'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='tarifas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Tarifas'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='valor_factory',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Factory'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='valor_pago_factory',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Pago Factory'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='valor_total_pago',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total Pago'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='vencimento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='contas.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='juros',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Juros'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='status',
            field=models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Original'),
        ),
        migrations.AddIndex(
            model_name='contasreceber',
            index=models.Index(fields=['data'], name='contas_rece_data_74c378_idx'),
        ),
        migrations.AddIndex(
            model_name='contasreceber',
            index=models.Index(fields=['vencimento'], name='contas_rece_vencime_f56798_idx'),
        ),
        migrations.AddIndex(
            model_name='contasreceber',
            index=models.Index(fields=['cliente'], name='contas_rece_cliente_a67add_idx'),
        ),
        migrations.AddIndex(
            model_name='contasreceber',
            index=models.Index(fields=['status'], name='contas_rece_status_f01ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='contasreceber',
            index=models.Index(fields=['data_pagamento'], name='contas_rece_data_pa_959f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='contasreceber',
            index=models.Index(fields=['nosso_numero'], name='contas_rece_nosso_n_99edb3_idx'),
        ),
        migrations.AddIndex(
            model_name='contasreceber',
            index=models.Index(fields=['documento'], name='contas_rece_documen_2991c3_idx'),
        ),
    ]
